repos:
  - repo: https://github.com/python/black.git
    rev: 24.2.0
    hooks:
      - id: black
        exclude: ^packages/
        args: [ '--line-length', '120']
        language_version: python3
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: ^packages/
        args: ['--max-line-length', '120', '--extend-ignore', 'E203,BLK100,W605']
        additional_dependencies:
          - flake8-black==0.2.4
          - flake8-thoughtful==0.1.0
        language_version: python3
  - repo: https://bitbucket.org/thoughtfulautomation/ta-commit-secure.git
    rev: 0.1.1
    hooks:
      - id: ta-commit-secure
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120", "--extend-skip", "__init__.py", "--filter-files",]